import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata= {
  title: "Create Next App",
  description: "Teste ",}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar bg-neutral text-neutral-content">
            <button className="btn btn-ghost text-xl">daisyUI</button>
        </div>

        <div className="navbar bg-base-300">
            <button className="btn btn-ghost text-xl">daisyUI</button>
        </div>

        <div className="navbar bg-primary text-primary-content">
            <button className="btn btn-ghost text-xl">daisyUI</button>
        </div>
        {children}
      </body>
    </html>
  );
}
